# Generated by Django 4.1 on 2022-09-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]

